config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    get 'admin/order' => 'orders#show'
    #patch 'order_details' => 'order_details#update'
    resources :orders
    resources :order_details, :only => [:update]
    resources :customers
    resources :genres
    resources :items
  end

  scope module: :public do
    root to: 'homes#top'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'orders/conplete' => 'orders#conplete'
    post 'orders/confirm' => 'orders#confirm'
    resources :addresses
    resources :orders
    resources :cart_items, :only => [:index, :create, :update, :destroy]
    resources :customers, :only => [:index, :create, :edit, :update, :destroy]
    resources :items
    resources :homes

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

    validates :item_id, :amount, presence: true
    validates :amount, numericality:{ only_integer: true }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_deleted == false)
  # end
  def name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end

    if !size.empty?
      image.variant(resize: size)
    else
      image
    end
  end
  def self.recommended
    recommends = []
    active_genres = Genre.all
    active_genres.each do |genre|
      item = genre.items.last
      recommends << item if item
    end
    recommends
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  # 注文モデル
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: {入金待ち:0,入金確認:1,制作中:2,発送準備中:3,発送済み:4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {製作不可:0,製作待ち:1,製作中:2,製作完了:3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "登録に成功しました"
      redirect_to admin_genres_path
    else
      flash[:warning] = "入力内容を確認してください"
  		render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
        flash[:notice] = "更新に成功しました"
        redirect_to admin_genres_path(@genre.id)
    else
        @genres = Genre.all
        render :edit
    end
  end

  private
  	def genre_params
  		params.require(:genre).permit(:name)
  	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    	before_action :authenticate_admin!
  def top
  	 @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    #@item.is_active = true
    if @item.save
      flash[:success] = "登録に成功しました"
      redirect_to admin_item_path(@item.id)
    else
      flash[:warning] = "入力内容を確認してください"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "更新に成功しました"
      redirect_to admin_items_path
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :price, :introduction, :genre_id, :is_active, :image)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:day]
      @orders = Order.created_at
    else
  	   @orders = Order.all
    end
  end

  def show
  	@order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end

  def update

  	@order = Order.find(params[:id])
    @order.update(order_params)
    flash[:success] = "更新に成功しました"
  	redirect_to admin_root_path
  end

  private
  def order_params
  	params.require(:order).permit(:postal_code, :addresses, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  # strong parameterで姓と名の属性(firstNameとlastName)をpermitする
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstName, :lastName])
  end
  def after_sign_in_path_for(resource)
   case resource
  			when Admin
    			admin_root_path
			  when Customer
				  items_path
   end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h3>ジャンル編集</h3>
<%= form_with model: @genre, url:admin_genre_path(@genre.id) do |f| %>
         <div class="form-group">
        　<label for="genre_name">ジャンル名</label><br>
        　<%= f.text_field :name, autofocus: true, id:"inputName" %>
         </div>
         <div class="form-group">
         <%= f.submit "変更を保存", class:"btn btn-success" %>
         </div>
<% end %>

app/views/admin/genres/index.html.erb
<style>
  .btn {
    width: 100px;
  }
  .change {
    display: none;
  }
  .show {
    display: inline-block;
  }
</style>

<div class="index-container" style="width:50%; margin: 20px auto;">

  <h3>ジャンル一覧・追加</h3>
  <%= form_with model: @genre, url:admin_genres_path do |f| %>
    <div class="form-group">
       <label for="genre">ジャンル名</label>
　　　　<%= f.text_field :name %>
        <%= f.submit '新規登録', class:"btn btn-success btn-info btn-md" %>
    </div>
  <% end %>

  <table class="table">
      <tr>ジャンル一覧</tr>

        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-sm btn-success" %></td>
        <% end %>
        </tbody>
      </tr>
  </table>

</div>

app/views/admin/items/edit.html.erb
<div class="row" style= "width: 80%; margin: 20px auto;">
  <%= form_with model: @item, url:admin_item_path, method: :patch do |f| %>
    <div class="form-horizontal">
      <h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品編集登録画面</h4>

      <div class="form-group">
        <label class="col-sm-2"></label>
        <div class="col-sm-10">
          <%= image_tag @item.image, size:"200x200",fallback: "no_image.jpg"%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">画像投稿</label>
        <div class="col-sm-10">
          <%= f.file_field :image  %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">商品名</label>
        <div class="col-sm-6">
          <%= f.text_field :name, class:"form-control", id:"InputName", autocomplete: "name" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">商品説明</label>
        <div class="col-sm-7">
          <%= f.text_area :introduction, class:"form-control", id:"InputIntroduction", autocomplete: "introduction", rows: 10 %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">ジャンル</label>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">税抜価格</label>
          <%= f.text_field :price, autofocus: true, autocomplete: "price" %>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">販売ステータス</label>
        <%= f.select :is_active,{販売中:true, 販売停止:false}%>
      </div>

      <div class="actions">
        <label class="col-sm-2 control-label"></label>
        <%= f.submit "登録する", class:"btn btn-primary btn-md" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<style>
 th {
 	background: #dad7d7;
 }
</style>



<div class="container" style="position:relative;">
<h2>商品一覧</h2>

<div style="position:absolute; top: 30px; right: 900px;">
	<%= link_to '新規登録', new_admin_item_path %>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>商品ID</th>
			<th>商品名</th>
			<th>税抜価格</th>
			<th>ジャンル</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.id %></td>
			<td>
				<% if item.image.attached? %>
					<%= image_tag item.image, size:"100x100" %>
				<% else %>
				  <%= image_tag 'no_image', size: "100x100" %>
				<% end %>
					<%= link_to admin_item_path(item.id) do %>
					<%= item.name %>
					<% end %>
			</td>
			<td><%= item.price %></td>
			<td><%= item.genre.name %></td>
			<td>
				<% if item.is_active? %>
					<span class="badge" style="background:#8BCE9A">販売中</span>
				<% else %>
					<span class="badge" style="background:#D52438">販売停止</span>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/items/new.html.erb
<div class="row" style= "width: 80%; margin: 20px auto;">
  <%= form_with model: @item, url:admin_items_path do |f| %>
    <div class="form-horizontal">
      <h4 style="margin-bottom: 20px; border-left: 2px solid #2D6F4C; padding: 10px;">商品新規登録</h4>
      <div class="form-group">
        <label class="col-sm-2 control-label">商品画像</label>
        <div class="col-sm-3">
          <%= f.file_field :image %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">商品名</label>
        <div class="col-sm-6">
          <%= f.text_field :name, class:"form-control", id:"InputName", autocomplete: "name" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">商品説明</label>
        <div class="col-sm-7">
          <%= f.text_area :introduction, class:"form-control", id:"InputIntroduction", autocomplete: "introduction", rows: 10 %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">ジャンル</label>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">税抜価格</label>
          <div class="col-sm-2">
            <%= f.text_field :price, autofocus: true, autocomplete: "price" %>
          </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">販売ステータス</label>
        <%= f.select :is_active,{販売中:true, 販売停止:false}%>
      </div>


      <div class="actions">
        <label class="col-sm-2 control-label"></label>
          <%= f.submit "登録する", class:"btn btn-primary btn-md" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>

    <div class="row" style="width: 90%; margin: 20px auto;">
  <div class="col-xs-1" ></div>
  <div class="col-xs-5" style ="margin: 100px 0 100px 0">
    <%= image_tag @item.image, size:"300x300" %>
  </div>
  <div class="col-xs-6" style ="margin: 100px 0 100px 0">

    <table class="table">

	  <tr>
		<th>商品名</th>
		<td><%= @item.name %></td>
	  </tr>

	  <tr>
		<th>商品説明</th>
		<td><%= @item.introduction %></td>
	  </tr>

	  <tr>
	    <th>ジャンル</th>
		<td><%= @item.genre.name %></td>
	  </tr>

	  <tr>
        <th>税込価格 （税抜価格）</th>
		<td><%= (@item.price * 1.1).floor %>   (<%= @item.price %>)  円</td>
	  </tr>

	  <tr>
	    <th>販売ステータス</th>
		<td>
		  <% if @item.is_active == true %>
		    販売中
		  <% elsif @item.is_active == false %>
		    販売停止
		  <% end %>
		</td>
	  </tr>
	  </table>

	  <%= link_to edit_admin_item_path(@item.id) do%>
		<label class="btn btn-info">編集する</label>
	  <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<style>
	h4 {
		border-left: 2px solid #2D6F4C;
		padding: 10px;
		}

	th {
		background: #dad7d7;
		border: 1px solid #fff;
		width: 25%;
	}

	.text {
		font-size: 12px;
		color: #2d714c;
	}
</style>

<div class="row" style="width:60%; margin:0 auto;">
<h4>注文履歴詳細</h4>
	<span class="text pull-right">表示金額は全て税込です。</span>
	<h5>注文情報</h5>
			<%= form_with model: @order, url: admin_order_path do |f| %>
<table class="table table-bordered ">
		<tr>
			<th>購入者</th>
			<td><%= link_to admin_customer_path(@customer.id) do %>
				<%= @customer.name %>
				<% end %>
			</td>
		</tr>
		<tr>
			<th>注文日</th>
			<td><%= @order.created_at.strftime('%Y年%m月%d日') %></td>
		</tr>
		<tr>
			<th>配送先</th>
			<td>
				〒<%= @order.postal_code %><br>
				<%= @order.addresses %><br>
				<%= @order.name %>様
			</td>
		</tr>
		<tr>
			<th>支払い方法</th>
			<td><%= @order.payment_method_i18n %></td>
		</tr>
		<tr>
			<th>ステータス</th>
			<td><%= f.select :status,{入金待ち:"入金待ち",入金確認:"入金確認",制作中:"制作中",発送準備中:"発送準備中",発送済み:"発送済み"}%></td>
			<td><%= f.submit "更新" %></td>

		</tr>
</table>
			<% end %>

<table class="table table-bordered">
	<tr style="background:#dad7d7; border: 1px solid #fff;">
		<th>商品名</th>
		<th>単価</th>
		<th>数量</th>
		<th>小計</th>
		<th>製造ステータス</th>
	</tr>
	<% total_price = 0 %>
	<% @order_details.each do |order_detail| %>
	 <tr>
	 	<td>
	 		<%= order_detail.item.name %>
	 	</td>
	 	<td>
	 		<%= hidden_field :item_id, value: order_detail.item.price %>
	 		<%= (order_detail.item.price*1.1).floor %>
	 	</td>
	 	<td>
	 		<%= order_detail.amount %>
	 	</td>
	 	<td>
	 		<%= hidden_field :item_id, value: order_detail.item.price %>
	 		<%= (order_detail.item.price*1.1*order_detail.amount).floor %>
	 	</td>
	 	<td>
	 		<%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
	 		<%= f.select :making_status,OrderDetail.making_statuses.keys %>
	 		<%= f.submit "更新" %>
	 		<% end %>
	 	</td>
	 </tr>
	<% end %>
</table>
</div>