config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: 'homes#top'
    get 'admin/order' => 'orders#show'
    #patch 'order_details' => 'order_details#update'
    resources :orders
    resources :order_details, :only => [:update]
    resources :customers
    resources :genres
    resources :items
  end

  scope module: :public do
    root to: 'homes#top'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'orders/conplete' => 'orders#conplete'
    post 'orders/confirm' => 'orders#confirm'
    resources :addresses
    resources :orders
    resources :cart_items, :only => [:index, :create, :update, :destroy]
    resources :customers, :only => [:index, :create, :edit, :update, :destroy]
    resources :items
    resources :homes

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer

    validates :item_id, :amount, presence: true
    validates :amount, numericality:{ only_integer: true }

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_deleted == false)
  # end
  def name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image(size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end

    if !size.empty?
      image.variant(resize: size)
    else
      image
    end
  end
  def self.recommended
    recommends = []
    active_genres = Genre.all
    active_genres.each do |genre|
      item = genre.items.last
      recommends << item if item
    end
    recommends
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  # 注文モデル
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: {入金待ち:0,入金確認:1,制作中:2,発送準備中:3,発送済み:4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {製作不可:0,製作待ち:1,製作中:2,製作完了:3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "登録に成功しました"
      redirect_to admin_genres_path
    else
      flash[:warning] = "入力内容を確認してください"
  		render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
        flash[:notice] = "更新に成功しました"
        redirect_to admin_genres_path(@genre.id)
    else
        @genres = Genre.all
        render :edit
    end
  end

  private
  	def genre_params
  		params.require(:genre).permit(:name)
  	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    	before_action :authenticate_admin!
  def top
  	 @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    #@item.is_active = true
    if @item.save
      flash[:success] = "登録に成功しました"
      redirect_to admin_item_path(@item.id)
    else
      flash[:warning] = "入力内容を確認してください"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "更新に成功しました"
      redirect_to admin_items_path
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :price, :introduction, :genre_id, :is_active, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  # strong parameterで姓と名の属性(firstNameとlastName)をpermitする
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstName, :lastName])
  end
  def after_sign_in_path_for(resource)
   case resource
  			when Admin
    			admin_root_path
			  when Customer
				  items_path
   end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_adminheader.html.erb
<style>
	ul {
		list-style: none;
	}

	li {
		display: inline-block;
		color:#694d49;
		margin-right: 10px;
	}
</style>



<div id="header" style="border-bottom:1px solid #dad7d7">

<% if admin_signed_in? %>
	<ul>
		<li><%= link_to '商品一覧', admin_items_path %></li>
		<li><%= link_to '会員一覧', admin_customers_path %></li>
		<li><%= link_to '注文履歴一覧', admin_root_path %></li>
		<li><%= link_to 'ジャンル一覧', admin_genres_path %></li>
		<li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
	</ul>
<% else %>
  <ul>
    <li><%= link_to 'About', about_path %></li>
		<li><%= link_to '商品一覧', items_path %></li>
		<li><%= link_to '新規登録', new_customer_registration_path %></li>
		<li><%= link_to 'ログイン', new_customer_session_path %></li>
  </ul>
<% end %>
</div>

app/views/layouts/_header.html.erb
<style>
	ul {
		list-style: none;
	}

	li {
		display: inline-block;
		color:#694d49;
		margin-right: 10px;
	}
</style>



<div id="header" style="border-bottom:1px solid #dad7d7">

<% if customer_signed_in? %>
	<ul>
		<li><%= link_to 'マイページ', customers_my_page_path %></li>
		<li><%= link_to '商品一覧',items_path %></li>
		<li><%= link_to 'カート', cart_items_path %></li>
		<li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
	</ul>
<% else %>
  <ul>
    <li><%= link_to 'About', about_path %></li>
		<li><%= link_to '商品一覧', items_path %></li>
		<li><%= link_to '新規登録', new_customer_registration_path %></li>
		<li><%= link_to 'ログイン', new_customer_session_path %></li>
  </ul>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div id="container">
    <header>
        <% if admin_signed_in? %>
            <%= render 'layouts/adminheader' %>
        <% else %>
            <%= render 'layouts/header' %>
        <% end %>
    </header>
   </div>
    <%= yield %>
  </body>
</html>